# Configuration for cargo-deny to allow common open source licenses

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0", 
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "Unicode-3.0",
]

# Confidence threshold for detecting a license from a license text
confidence-threshold = 0.8

# Allow specific licenses on a per-crate basis
# exceptions = []

[licenses.private]
# Ignore workspace crates that aren't published
ignore = true

[bans]
# Allow multiple versions of the same crate with warning
multiple-versions = "warn"

[advisories]
# Ignore specific advisories
ignore = [
    "RUSTSEC-2024-0436", # paste crate unmaintained but widely used
]

[sources]
# Allow standard crates.io registry
allow-registry = ["https://github.com/rust-lang/crates.io-index"]