use ark_bn254::{Fq, Fq2, Fr, G1Affine, G1Projective, G2Affine, G2Projective};
use ark_ff::{PrimeField, UniformRand};
use ark_std::{str::FromStr, One};
use rust_kzg_bn254::{
    consts::{BYTES_PER_FIELD_ELEMENT, SIZE_OF_G1_AFFINE_COMPRESSED},
    helpers::{
        blob_to_polynomial, convert_by_padding_empty_byte, get_num_element, is_on_curve_g1,
        is_on_curve_g2, remove_empty_byte_from_padded_bytes_unchecked, set_bytes_canonical,
        set_bytes_canonical_manual, to_byte_array, to_fr_array,
    },
};

const GETTYSBURG_ADDRESS_BYTES: &[u8] = "Fourscore and seven years ago our fathers brought forth, on this continent, a new nation, conceived in liberty, and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived, and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting-place for those who here gave their lives, that that nation might live. It is altogether fitting and proper that we should do this. But, in a larger sense, we cannot dedicate, we cannot consecrate—we cannot hallow—this ground. The brave men, living and dead, who struggled here, have consecrated it far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us—that from these honored dead we take increased devotion to that cause for which they here gave the last full measure of devotion—that we here highly resolve that these dead shall not have died in vain—that this nation, under God, shall have a new birth of freedom, and that government of the people, by the people, for the people, shall not perish from the earth.".as_bytes();

#[test]
fn test_g1_is_on_curve() {
    use rand::thread_rng;

    let rng = &mut thread_rng();
    for _ in 0..1000 {
        let point = G1Affine::rand(rng);
        assert!(is_on_curve_g1(&G1Projective::from(point)));
        let mut not_on_curve = point;
        not_on_curve.x += Fq::one();
        assert!(!is_on_curve_g1(&G1Projective::from(not_on_curve)));
    }
}

#[test]
fn test_g2_is_on_curve() {
    use rand::thread_rng;

    let rng = &mut thread_rng();
    for _ in 0..1000 {
        let point = G2Affine::rand(rng);
        assert!(is_on_curve_g2(&G2Projective::from(point)));
        let mut not_on_curve = point;
        not_on_curve.x += Fq2::one();
        assert!(!is_on_curve_g2(&G2Projective::from(not_on_curve)));
    }
}
// Loads data from files. This data was generated by gnark and is DA compatible.
// Tests deserialization of data and equivalence.
#[test]
fn test_blob_to_polynomial() {
    use ark_serialize::Read;
    use std::{
        fs::File,
        io::{BufRead, BufReader},
    };

    let file = File::open("tests/test-files/blobs.txt").unwrap();
    let mut reader = BufReader::new(file);
    let mut buffer = [0u8; SIZE_OF_G1_AFFINE_COMPRESSED];
    let mut read_fr_from_bytes: Vec<Fr> = vec![];
    let mut fr_from_str_vec: Vec<Fr> = vec![];

    // Loop to read the file 32 bytes at a time
    loop {
        match reader.read(&mut buffer[..]) {
            Ok(0) => {
                // No more data to read
                break;
            },
            Ok(n) => {
                // Process the chunk of data just read
                read_fr_from_bytes.push(Fr::from_be_bytes_mod_order(&buffer[..n]))
            },
            Err(e) => panic!("{}", e),
        }
    }

    let file2 = File::open("tests/test-files/blobs-from-fr.txt").unwrap();
    let reader2 = BufReader::new(file2);
    for (i, line) in reader2.lines().enumerate() {
        let line = line.unwrap();
        let trimmed_line = line.trim_end(); // Trim whitespace from the end
        let the_strings_str: Vec<&str> = trimmed_line.split(',').collect(); // Split the line on commas
        let fr_from_str = Fr::from_str(the_strings_str[0]).expect("should be fine");
        fr_from_str_vec.push(fr_from_str);
        assert_eq!(fr_from_str, read_fr_from_bytes[i]);
    }

    let mut file3 = File::open("tests/test-files/blobs.txt").unwrap();
    let mut contents = Vec::new();
    file3.read_to_end(&mut contents).unwrap();

    assert_eq!(fr_from_str_vec, blob_to_polynomial(&contents));
}

#[test]
fn test_to_fr_array() {
    let converted = convert_by_padding_empty_byte(
        vec![
            42, 212, 238, 227, 192, 237, 178, 128, 19, 108, 50, 204, 87, 81, 63, 120, 232, 27, 116,
            108, 74, 168, 109, 84, 89, 9, 6, 233, 144, 200, 125, 40,
        ]
        .as_slice(),
    );
    let data_fr = to_fr_array(&converted);
    let result = to_byte_array(&data_fr, converted.len().try_into().unwrap());
    assert_eq!(converted, result, "should be deserialized properly");

    let ga_converted = convert_by_padding_empty_byte(GETTYSBURG_ADDRESS_BYTES);
    let ga_converted_fr = to_fr_array(&ga_converted);
    assert_eq!(
        to_byte_array(&ga_converted_fr, ga_converted.len().try_into().unwrap()),
        ga_converted
    );
}

#[test]
fn test_how_to_read_bytes() {
    let the_bytes = vec![
        31, 94, 220, 111, 30, 251, 22, 93, 69, 166, 84, 121, 141, 75, 170, 165, 14, 59, 77, 36, 24,
        41, 19, 174, 245, 17, 10, 21, 88, 14, 186, 173,
    ];
    let data = Fr::from_be_bytes_mod_order(&the_bytes);
    println!("{:?}", data.0);
}

#[test]
fn test_get_num_element() {
    let num_elements = get_num_element(1000, BYTES_PER_FIELD_ELEMENT);
    assert_eq!(num_elements, 32_usize, "needs to be equal");
}

#[test]
fn test_set_canonical_bytes() {
    let data: Vec<u8> = vec![
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
        25, 26, 27, 28, 29, 30, 31,
    ];
    let fr_element = set_bytes_canonical_manual(&data);
    assert_eq!(fr_element, set_bytes_canonical(&data), "needs to be equal");
}

#[test]
fn test_convert_by_padding_empty_byte() {
    let mut padded_data = convert_by_padding_empty_byte("hi".as_bytes());
    assert_eq!(padded_data, vec![0, 104, 105], "testing adding padding");

    let mut unpadded_data = remove_empty_byte_from_padded_bytes_unchecked(&padded_data);
    assert_eq!(unpadded_data, vec![104, 105], "testing removing padding");

    let result: Vec<u8> = vec![
        0, 70, 111, 117, 114, 115, 99, 111, 114, 101, 32, 97, 110, 100, 32, 115, 101, 118, 101,
        110, 32, 121, 101, 97, 114, 115, 32, 97, 103, 111, 32, 111, 0, 117, 114, 32, 102, 97, 116,
        104, 101, 114, 115, 32, 98, 114, 111, 117, 103, 104, 116, 32, 102, 111, 114, 116, 104, 44,
        32, 111, 110, 32, 116, 104, 0, 105, 115, 32, 99, 111, 110, 116, 105, 110, 101, 110, 116,
        44, 32, 97, 32, 110, 101, 119, 32, 110, 97, 116, 105, 111, 110, 44, 32, 99, 111, 110, 0,
        99, 101, 105, 118, 101, 100, 32, 105, 110, 32, 108, 105, 98, 101, 114, 116, 121, 44, 32,
        97, 110, 100, 32, 100, 101, 100, 105, 99, 97, 116, 101, 0, 100, 32, 116, 111, 32, 116, 104,
        101, 32, 112, 114, 111, 112, 111, 115, 105, 116, 105, 111, 110, 32, 116, 104, 97, 116, 32,
        97, 108, 108, 32, 109, 0, 101, 110, 32, 97, 114, 101, 32, 99, 114, 101, 97, 116, 101, 100,
        32, 101, 113, 117, 97, 108, 46, 32, 78, 111, 119, 32, 119, 101, 32, 97, 114, 0, 101, 32,
        101, 110, 103, 97, 103, 101, 100, 32, 105, 110, 32, 97, 32, 103, 114, 101, 97, 116, 32, 99,
        105, 118, 105, 108, 32, 119, 97, 114, 44, 0, 32, 116, 101, 115, 116, 105, 110, 103, 32,
        119, 104, 101, 116, 104, 101, 114, 32, 116, 104, 97, 116, 32, 110, 97, 116, 105, 111, 110,
        44, 32, 111, 0, 114, 32, 97, 110, 121, 32, 110, 97, 116, 105, 111, 110, 32, 115, 111, 32,
        99, 111, 110, 99, 101, 105, 118, 101, 100, 44, 32, 97, 110, 100, 32, 0, 115, 111, 32, 100,
        101, 100, 105, 99, 97, 116, 101, 100, 44, 32, 99, 97, 110, 32, 108, 111, 110, 103, 32, 101,
        110, 100, 117, 114, 101, 46, 32, 0, 87, 101, 32, 97, 114, 101, 32, 109, 101, 116, 32, 111,
        110, 32, 97, 32, 103, 114, 101, 97, 116, 32, 98, 97, 116, 116, 108, 101, 45, 102, 105, 0,
        101, 108, 100, 32, 111, 102, 32, 116, 104, 97, 116, 32, 119, 97, 114, 46, 32, 87, 101, 32,
        104, 97, 118, 101, 32, 99, 111, 109, 101, 32, 116, 0, 111, 32, 100, 101, 100, 105, 99, 97,
        116, 101, 32, 97, 32, 112, 111, 114, 116, 105, 111, 110, 32, 111, 102, 32, 116, 104, 97,
        116, 32, 102, 105, 0, 101, 108, 100, 44, 32, 97, 115, 32, 97, 32, 102, 105, 110, 97, 108,
        32, 114, 101, 115, 116, 105, 110, 103, 45, 112, 108, 97, 99, 101, 32, 102, 0, 111, 114, 32,
        116, 104, 111, 115, 101, 32, 119, 104, 111, 32, 104, 101, 114, 101, 32, 103, 97, 118, 101,
        32, 116, 104, 101, 105, 114, 32, 108, 105, 0, 118, 101, 115, 44, 32, 116, 104, 97, 116, 32,
        116, 104, 97, 116, 32, 110, 97, 116, 105, 111, 110, 32, 109, 105, 103, 104, 116, 32, 108,
        105, 118, 0, 101, 46, 32, 73, 116, 32, 105, 115, 32, 97, 108, 116, 111, 103, 101, 116, 104,
        101, 114, 32, 102, 105, 116, 116, 105, 110, 103, 32, 97, 110, 100, 0, 32, 112, 114, 111,
        112, 101, 114, 32, 116, 104, 97, 116, 32, 119, 101, 32, 115, 104, 111, 117, 108, 100, 32,
        100, 111, 32, 116, 104, 105, 115, 46, 0, 32, 66, 117, 116, 44, 32, 105, 110, 32, 97, 32,
        108, 97, 114, 103, 101, 114, 32, 115, 101, 110, 115, 101, 44, 32, 119, 101, 32, 99, 97,
        110, 0, 110, 111, 116, 32, 100, 101, 100, 105, 99, 97, 116, 101, 44, 32, 119, 101, 32, 99,
        97, 110, 110, 111, 116, 32, 99, 111, 110, 115, 101, 99, 114, 0, 97, 116, 101, 226, 128,
        148, 119, 101, 32, 99, 97, 110, 110, 111, 116, 32, 104, 97, 108, 108, 111, 119, 226, 128,
        148, 116, 104, 105, 115, 32, 103, 0, 114, 111, 117, 110, 100, 46, 32, 84, 104, 101, 32, 98,
        114, 97, 118, 101, 32, 109, 101, 110, 44, 32, 108, 105, 118, 105, 110, 103, 32, 97, 110, 0,
        100, 32, 100, 101, 97, 100, 44, 32, 119, 104, 111, 32, 115, 116, 114, 117, 103, 103, 108,
        101, 100, 32, 104, 101, 114, 101, 44, 32, 104, 97, 118, 0, 101, 32, 99, 111, 110, 115, 101,
        99, 114, 97, 116, 101, 100, 32, 105, 116, 32, 102, 97, 114, 32, 97, 98, 111, 118, 101, 32,
        111, 117, 114, 32, 0, 112, 111, 111, 114, 32, 112, 111, 119, 101, 114, 32, 116, 111, 32,
        97, 100, 100, 32, 111, 114, 32, 100, 101, 116, 114, 97, 99, 116, 46, 32, 84, 0, 104, 101,
        32, 119, 111, 114, 108, 100, 32, 119, 105, 108, 108, 32, 108, 105, 116, 116, 108, 101, 32,
        110, 111, 116, 101, 44, 32, 110, 111, 114, 32, 0, 108, 111, 110, 103, 32, 114, 101, 109,
        101, 109, 98, 101, 114, 32, 119, 104, 97, 116, 32, 119, 101, 32, 115, 97, 121, 32, 104,
        101, 114, 101, 44, 0, 32, 98, 117, 116, 32, 105, 116, 32, 99, 97, 110, 32, 110, 101, 118,
        101, 114, 32, 102, 111, 114, 103, 101, 116, 32, 119, 104, 97, 116, 32, 116, 0, 104, 101,
        121, 32, 100, 105, 100, 32, 104, 101, 114, 101, 46, 32, 73, 116, 32, 105, 115, 32, 102,
        111, 114, 32, 117, 115, 32, 116, 104, 101, 32, 0, 108, 105, 118, 105, 110, 103, 44, 32,
        114, 97, 116, 104, 101, 114, 44, 32, 116, 111, 32, 98, 101, 32, 100, 101, 100, 105, 99, 97,
        116, 101, 100, 0, 32, 104, 101, 114, 101, 32, 116, 111, 32, 116, 104, 101, 32, 117, 110,
        102, 105, 110, 105, 115, 104, 101, 100, 32, 119, 111, 114, 107, 32, 119, 104, 0, 105, 99,
        104, 32, 116, 104, 101, 121, 32, 119, 104, 111, 32, 102, 111, 117, 103, 104, 116, 32, 104,
        101, 114, 101, 32, 104, 97, 118, 101, 32, 116, 0, 104, 117, 115, 32, 102, 97, 114, 32, 115,
        111, 32, 110, 111, 98, 108, 121, 32, 97, 100, 118, 97, 110, 99, 101, 100, 46, 32, 73, 116,
        32, 105, 0, 115, 32, 114, 97, 116, 104, 101, 114, 32, 102, 111, 114, 32, 117, 115, 32, 116,
        111, 32, 98, 101, 32, 104, 101, 114, 101, 32, 100, 101, 100, 105, 0, 99, 97, 116, 101, 100,
        32, 116, 111, 32, 116, 104, 101, 32, 103, 114, 101, 97, 116, 32, 116, 97, 115, 107, 32,
        114, 101, 109, 97, 105, 110, 105, 0, 110, 103, 32, 98, 101, 102, 111, 114, 101, 32, 117,
        115, 226, 128, 148, 116, 104, 97, 116, 32, 102, 114, 111, 109, 32, 116, 104, 101, 115, 101,
        32, 0, 104, 111, 110, 111, 114, 101, 100, 32, 100, 101, 97, 100, 32, 119, 101, 32, 116, 97,
        107, 101, 32, 105, 110, 99, 114, 101, 97, 115, 101, 100, 32, 0, 100, 101, 118, 111, 116,
        105, 111, 110, 32, 116, 111, 32, 116, 104, 97, 116, 32, 99, 97, 117, 115, 101, 32, 102,
        111, 114, 32, 119, 104, 105, 99, 0, 104, 32, 116, 104, 101, 121, 32, 104, 101, 114, 101,
        32, 103, 97, 118, 101, 32, 116, 104, 101, 32, 108, 97, 115, 116, 32, 102, 117, 108, 108,
        32, 0, 109, 101, 97, 115, 117, 114, 101, 32, 111, 102, 32, 100, 101, 118, 111, 116, 105,
        111, 110, 226, 128, 148, 116, 104, 97, 116, 32, 119, 101, 32, 104, 0, 101, 114, 101, 32,
        104, 105, 103, 104, 108, 121, 32, 114, 101, 115, 111, 108, 118, 101, 32, 116, 104, 97, 116,
        32, 116, 104, 101, 115, 101, 32, 100, 0, 101, 97, 100, 32, 115, 104, 97, 108, 108, 32, 110,
        111, 116, 32, 104, 97, 118, 101, 32, 100, 105, 101, 100, 32, 105, 110, 32, 118, 97, 105,
        110, 0, 226, 128, 148, 116, 104, 97, 116, 32, 116, 104, 105, 115, 32, 110, 97, 116, 105,
        111, 110, 44, 32, 117, 110, 100, 101, 114, 32, 71, 111, 100, 44, 0, 32, 115, 104, 97, 108,
        108, 32, 104, 97, 118, 101, 32, 97, 32, 110, 101, 119, 32, 98, 105, 114, 116, 104, 32, 111,
        102, 32, 102, 114, 101, 101, 0, 100, 111, 109, 44, 32, 97, 110, 100, 32, 116, 104, 97, 116,
        32, 103, 111, 118, 101, 114, 110, 109, 101, 110, 116, 32, 111, 102, 32, 116, 104, 101, 0,
        32, 112, 101, 111, 112, 108, 101, 44, 32, 98, 121, 32, 116, 104, 101, 32, 112, 101, 111,
        112, 108, 101, 44, 32, 102, 111, 114, 32, 116, 104, 101, 0, 32, 112, 101, 111, 112, 108,
        101, 44, 32, 115, 104, 97, 108, 108, 32, 110, 111, 116, 32, 112, 101, 114, 105, 115, 104,
        32, 102, 114, 111, 109, 32, 0, 116, 104, 101, 32, 101, 97, 114, 116, 104, 46,
    ];

    padded_data = convert_by_padding_empty_byte(GETTYSBURG_ADDRESS_BYTES);
    assert_eq!(padded_data, result, "testing adding padding");

    unpadded_data = remove_empty_byte_from_padded_bytes_unchecked(&padded_data);

    assert_eq!(
        unpadded_data, GETTYSBURG_ADDRESS_BYTES,
        "testing adding padding"
    );
}

#[cfg(test)]
mod tests {
    use rust_kzg_bn254::helpers::is_zeroed;

    #[test]
    fn test_is_zeroed_all_zeroes() {
        // Case where the first byte and the buffer are all zeroes
        let first_byte = 0;
        let buf = vec![0, 0, 0, 0, 0];
        assert!(is_zeroed(first_byte, buf), "Expected true for all zeroes");
    }

    #[test]
    fn test_is_zeroed_first_byte_non_zero() {
        // Case where the first byte is non-zero
        let first_byte = 1;
        let buf = vec![0, 0, 0, 0, 0];
        assert!(
            !is_zeroed(first_byte, buf),
            "Expected false when the first byte is non-zero"
        );
    }

    #[test]
    fn test_is_zeroed_buffer_non_zero() {
        // Case where the buffer contains non-zero elements
        let first_byte = 0;
        let buf = vec![0, 0, 1, 0, 0];
        assert!(
            !is_zeroed(first_byte, buf),
            "Expected false when the buffer contains non-zero elements"
        );
    }

    #[test]
    fn test_is_zeroed_first_byte_and_buffer_non_zero() {
        // Case where both the first byte and buffer contain non-zero elements
        let first_byte = 1;
        let buf = vec![0, 1, 0, 0, 0];
        assert!(
            !is_zeroed(first_byte, buf),
            "Expected false when both the first byte and buffer contain non-zero elements"
        );
    }

    #[test]
    fn test_is_zeroed_empty_buffer() {
        // Case where the buffer is empty but the first byte is zero
        let first_byte = 0;
        let buf: Vec<u8> = Vec::new();
        assert!(
            is_zeroed(first_byte, buf),
            "Expected true for an empty buffer with a zero first byte"
        );
    }

    #[test]
    fn test_is_zeroed_empty_buffer_non_zero_first_byte() {
        // Case where the buffer is empty and the first byte is non-zero
        let first_byte = 1;
        let buf: Vec<u8> = Vec::new();
        assert!(
            !is_zeroed(first_byte, buf),
            "Expected false for an empty buffer with a non-zero first byte"
        );
    }
}
