on:
  workflow_dispatch:
  
jobs:
  crates-publish:
    runs-on: ubuntu-latest
    environment: crates-release-prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Set Up Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 #1.10.1
        with:
          toolchain: stable
          override: true

      - name: Publish Crate
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
