name: crate-release-prod
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      crate_name:
        description: "Crate to publish"
        required: true
        type: choice
        options:
          - rust-kzg-bn254-primitives
          - rust-kzg-bn254-verifier
          - rust-kzg-bn254-prover

jobs:
  crates-publish:
    runs-on: ubuntu-latest
    environment: crates-release-prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Publish Crate
        run: cargo publish -p ${{ inputs.crate_name }} --token ${{ secrets.CRATES_IO_TOKEN }}

