name: Cargo Audit Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
  schedule:
    # Run dependency updates weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
        
  cargo-audit-scan:
    name: Cargo Audit Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
      with:
        disable-sudo: false
        egress-policy: block
        allowed-endpoints: >
          archive.ubuntu.com:80
          auth.docker.io:443
          github.com:443
          index.crates.io:443
          objects.githubusercontent.com:443
          packages.microsoft.com:443
          production.cloudflare.docker.com:443
          registry-1.docker.io:443
          security.ubuntu.com:80
          static.crates.io:443
          static.rust-lang.org:443
          
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@1.78
      
    - name: Install security tools
      run: |
        # Install pre-compiled binaries compatible with Rust 1.78
        # cargo-audit
        curl -L https://github.com/RustSec/rustsec/releases/download/cargo-audit/v0.18.3/cargo-audit-x86_64-unknown-linux-musl-v0.18.3.tgz | tar xz
        find . -name "cargo-audit" -type f -exec sudo cp {} /usr/local/bin/ \;
        # cargo-deny  
        curl -L https://github.com/EmbarkStudios/cargo-deny/releases/download/0.14.24/cargo-deny-0.14.24-x86_64-unknown-linux-musl.tar.gz | tar xz
        find . -name "cargo-deny" -type f -exec sudo cp {} /usr/local/bin/ \;
        # Verify installations
        cargo-audit --version
        cargo-deny --version
        
    - name: Run security audit
      run: cargo audit
      
    - name: Run cargo deny
      run: cargo deny check

